Xcode 14 - Warnings related to iOS 11 support (Swift Package Manager)
AliSoftware/OHHTTPStubs pull request #352
Opened 2022-07-17 16:12 UTC by kikeenrique

### Checklist

- [x] I've checked that all new and existing tests pass
- [x] I've updated the documentation if necessary
- [x] I've added an entry in the CHANGELOG to credit myself

### Description

Hi,
I would like to contribute fixing a recent warning.

The new Xcode 14 uses next SDKs as base: iOS 11.0, macOS 10.13, watchOS 4.0 and tvOS 11.0. Compiling in this Xcode shows a warning.
Handle this restrictions relying on swift version (which is also vinculated to each Xcode version).

Regards and comments welcomed

### Motivation and Context

Fixes a warning

Run project tests.

2022-09-27 16:22 UTC, kishorepran approved these changes

2023-07-15 07:12 UTC, kishorepran requested changes
We need to update this for cocoa pods as well

2024-02-04 13:21 UTC, kikeenrique commented
I think as half of the changes are already included in https://github.com/AliSoftware/OHHTTPStubs/pull/352 this PR could be discarded when the other is merged.

2024-03-07 12:00 UTC, Liquidsoul commented
Thank you for your contribution!

Since #361 was merged I am closing this. If some of these changes are still required, please do not hesitate to open another PR!

2024-03-07 12:00 UTC, closed without merging